# 로그인, 로그아웃, 회원가입 엔티티 조인 완료
heekuukuu/study-together pull request #3
Opened 2024-10-08 13:32 UTC by heekuukuu

### 변경 사항
- [X] 신규 기능 추가 
- [ ] 버그 수정 
- [ ] 리펙토링
- [ ] 테스트 
- [ ] 문서 업데이트 
- [ ] 기타

### 작업 내역
- 로그인, 로그아웃, 토큰갱신,회원가입 기능의 엔티티 조인 작업 완료

### 테스트
- [ X ] API 테스트 
- [ ] 테스트 코드 작성

## 문제 및 해결
- 맵핑오류해결 

## 다음 진행사항
- API 테스트 및 테스트 코드 작성 진행 예정

2024-10-10 05:19 UTC, handyejee requested changes

2024-10-10 05:19 UTC, handyejee commented on src/main/java/helloworld/studytogether/user/entity/User.java
> +    @Column(nullable = false, unique = true)
`@Id` 어노테이션은 PK 값 설정 하는거기 때문에 데이터베이스에 들어갈때 nullable = false, unique = true 설정이 반영되기 때문에 불필요해 보입니다!

2024-10-10 05:19 UTC, handyejee commented on src/main/java/helloworld/studytogether/user/entity/User.java
> +;
여기서 ; 부분이 잘못 추가 된것 같은데 확인 부탁드립니다!

2024-10-10 05:19 UTC, handyejee commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
token 테이블에 token_id 컬럼으로 들어가기 위한 `@Column( name= token_id)` 속성이 추가 되어야 할것 같습니다.

2024-10-10 05:47 UTC, ddoddoloo commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
제가 발견을 못한건지 모르겠지만... 만료된 토큰을 주기적으로 정리하는 로직을 추가하는 것은 어떨까요?  RefreshToken 엔티티에 expiresAt 필드를 추가하고 RefreshTokenRepository에 만료된 토큰을 삭제하는 메서드를 정의하면 주기적으로 만료된 토큰을 정리할 수 있습니다.

2024-10-10 05:54 UTC, ddoddoloo commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
사용자가 잘못된 자격 증명을 입력했거나, 예기치 않은 에러가 발생했을 때 예외를 처리하는 기능을 넣으면 좋을 것 같습니다. 예외가 발생할 경우 401 Unauthorized 상태 코드를 반환하고, 로그를 남기는 것은 어떨까요?  현재 생각나는 방법으로는 catch와 HashMap을 쓰는 방법 정도가 있는데 더 좋은 방법이 있는지는 좀 더 고민해야 할 것 같아요.

2024-10-10 05:54 UTC, ddoddoloo commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
여기에도 추가적으로 500 Internal Server Error 상태 코드와 함께 메시지 반환하면 좋을 것 같습니다. 토큰 생성 및 저장 실패가 예시가 될 수 있겠네요. Token generation failed 같은 메시지도 같이 올려주면 좋을 것 같습니다.

2024-10-10 06:01 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
로그아웃하면 토큰이 삭제되게 만들었는데 굳이 저장을 하는게 좋을까요?

2024-10-10 06:02 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
네

2024-10-10 06:37 UTC, handyejee commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
아 제가 얘기드린 부분은 컬럼명은 tokenId가 맞지만 데이터베이스에 저장할때는 token_id 로 저장하기로 해서 그렇게 매핑되는 컬럼 속성이 필요하지 않을까 였습니다!

2024-10-10 06:38 UTC, handyejee commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
@heekuukuu @ddoddoloo 예외 부분은 이번 pr에서 제외하고 이 부분 적어뒀다가 추가 개선으로 수정하면 어떨까요 ?

2024-10-10 10:36 UTC, ddoddoloo commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
좋을 것 같아요. 이건 추가적인 것이여서 나중에도 넣을 수 있는 것이니까요!

2024-10-11 00:38 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/user/entity/User.java
> +    @Column(nullable = false, unique = true)
수정하였습니다.

2024-10-11 00:38 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/user/entity/User.java
> +;
수정하였습니다.

2024-10-11 00:38 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/token/entity/RefreshToken.java
>    @GeneratedValue(strategy = GenerationType.IDENTITY)
수정하였습니다.

2024-10-11 00:38 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
수정하였습니다.

2024-10-11 00:45 UTC, heekuukuu commented on src/main/java/helloworld/studytogether/jwt/filter/LoginFilter.java
> +
추후 수정예정

2024-10-11 02:13 UTC, merged